config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home#index'
  post '/calculate', to: 'home#calculate', as: 'calculate'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :discountable_from, class_name: 'Item'
  belongs_to :discountable_to, class_name: 'Item'

  validates :amount, presence: true
  validates :discountable_from_id, presence: true, uniqueness: { scope: :discountable_to_id }
  validate :item_uniqueness

  scope :with_items, -> (item_ids) { where(discountable_from_id: item_ids).or(where(discountable_to_id: item_ids)) }

  def items
    [discountable_from, discountable_to].sort_by(&:price).reverse
  end

  def price
    (items.first.price * amount/100.0).to_i
  end

  def discountable(item)
    [discountable_from, discountable_to].excluding(item).first
  end

  def self.find_with_items(from_id, to_id)
    find_by(discountable_from_id: from_id, discountable_to_id: to_id) || find_by(discountable_from_id: to_id, discountable_to_id: from_id)
  end

  def self.by_items
    item_ids = Discount.all.pluck(:discountable_from_id, :discountable_to_id).flatten.uniq
    items = Item.find(item_ids)

    result = {}

    items.map do |item|
      discounts = item.discounts - result.values.flatten

      result[item] = discounts if discounts.present?
    end

    result
  end

  private

  def item_uniqueness
    errors.add(:base, message: 'Same items. You have to select different items.') if discountable_from_id == discountable_to_id
    errors.add(:base, message: 'Discount with the items already exist.') if Discount.where(discountable_from_id: discountable_to_id, discountable_to_id: discountable_from_id).present?
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :price, presence: true

  default_scope { order(price: :desc) }

  def discounts
    Discount.where(discountable_from_id: id).or(Discount.where(discountable_to_id: id))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @items = Item.all
    @discounts = Discount.by_items
  end

  def calculate
    items_h = params[:items].select{|k,v| v.present?}.to_enum.to_h
    item_ids = items_h.keys

    @orders = Hash[items_h.map{ |id, quantity| [Item.find_by(id: id), quantity.to_i] }]

    @sub_total = @orders.map{|item, quantity| item.price * quantity}.sum

    discounts = Discount.with_items(item_ids).sort_by(&:price).reverse
    @available_discounts = {}

    discounts.each do |discount|
      next if @orders[discount.discountable_from].to_i == 0
      next if @orders[discount.discountable_to].to_i == 0

      loop do
        break if @orders[discount.discountable_from].to_i == 0 || @orders[discount.discountable_to].to_i == 0

        @orders[discount.discountable_from] -= 1
        @orders[discount.discountable_to] -= 1

        @available_discounts[discount] ||= 0
        @available_discounts[discount] += 1
      end
    end

    @total = @sub_total - @available_discounts.map{|discount, quantity| discount.price * quantity}.sum

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def order_params
    params.permit(:items)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def item_discounts(item, discounts)
    return unless discounts[item]

    discounts[item]&.collect do |discount|
      discountable = discount.discountable(item)
      content_tag(:small, "#{number_to_currency((item.price - discount.price)/100.0, :unit => '$')} (with a #{discountable.name})", class: 'block')
    end.join.html_safe
  end

  def discount_price(discount, quantity)
    -discount.price * quantity/100.0
  end

  def discount_detail(discount, quantity)
    "#{discount.amount}%(#{discount.discountable_from.name},#{discount.discountable_to.name}) x #{quantity}"
  end
end

app/views/home/_confirmed.slim
.flex.items-center.justify-center.h-screen
  .flex.flex-col.items-center.space-y-2
    svg.text-green-600.w-28.h-28[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="1"]
      path[stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"]
    h1.text-4xl.font-bold
      | Thank You !
    p
      | Thank you for your orders! Your orders will be ready in some minutes.
    = link_to root_path, class: 'inline-flex items-center px-4 py-2 text-white bg-indigo-600 border border-indigo-600 rounded rounded-full hover:bg-indigo-700 focus:outline-none focus:ring' do
      svg.w-3.h-3.mr-2[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke="currentColor" stroke-width="2"]
        path[stroke-linecap="round" stroke-linejoin="round" d="M7 16l-4-4m0 0l4-4m-4 4h18"]
      span.text-sm.font-medium
        |  Home 

app/views/home/calculate.turbo_stream.slim
- if params[:commit].present? && @total > 0
  = turbo_stream.update 'items' do
    = render 'confirmed'
- else
  = turbo_stream.update 'sub_total' do
    = number_to_currency(@sub_total/100.0, :unit => '$')
  = turbo_stream.update 'discount_details' do
    = render 'items/discount_details', discounts: @available_discounts
  = turbo_stream.update 'discount_prices' do
    = render 'items/discount_prices', discounts: @available_discounts
  = turbo_stream.update 'total' do
    = number_to_currency(@total/100.0, :unit => '$')
  = turbo_stream.update 'submit_area' do
    - if @total > 0
      = submit_tag 'Confirm Order', class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
    - else
      = submit_tag 'Confirm Order', disabled: true, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium opacity-50 cursor-not-allowed"

app/views/home/index.slim
.flex.flex-wrap.justify-center.my-12
  .w-auto
    = turbo_frame_tag 'items' do
      .flex.justify-between.items-baseline.mb-6[data-controller="extended-modal" data-extended-modal-prevent-default-action-opening="false"]
        h1.text-3xl.text-gray-900
          | Zernyu Coffee Shop
      .overflow-x-auto.relative.shadow-md.sm:rounded-lg
        - if @items.present?
          = form_tag calculate_path, id: 'order-form', data: {controller: 'orders'} do
            table.w-full.text-sm.text-left.text-gray-500.dark:text-gray-400[data-action="click->orders#connect"]
              thead.text-xs.text-gray-700.uppercase.bg-gray-50.dark:bg-gray-700.dark:text-gray-400
                tr
                  th.py-3.px-6[scope="col"] Name
                  th.py-3.px-6[scope="col"] Price
                  th.py-3.px-6[scope="col"] Qty
              tbody
                = render @items, discounts: @discounts
              tfoot
                tr
                  th.py-3.px-6.text-base[scope="row"] Subtotal
                  td
                  td.py-3.px-6
                    = turbo_frame_tag 'sub_total'
                tr              
                  th.py-3.px-6.text-base[scope="row"] Discount
                  td.py-3.px-6
                    = turbo_frame_tag 'discount_details'
                  td.py-3.px-6
                    = turbo_frame_tag 'discount_prices'
                tr.font-semibold.text-gray-900.dark:text-white
                  th.py-3.px-6.text-base[scope="row"] Total
                  td
                  td.py-3.px-6
                    = turbo_frame_tag 'total'
                tr
                  th
                  td
                  td.py-3.px-6
                    = turbo_frame_tag 'submit_area' do
                      = submit_tag 'Confirm Order', disabled: true, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium opacity-50 cursor-not-allowed"
        - else
          p There is no available item

app/views/items/_discount_details.slim
- discounts.each do |discount, quantity|
  p= discount_detail(discount, quantity)

app/views/items/_discount_prices.slim
- discounts.each do |discount, quantity|
  p= number_to_currency(discount_price(discount, quantity), :unit => '$')

app/views/items/_item.slim
tr.bg-white.border-b.dark:bg-gray-800.dark:border-gray-700.hover:bg-gray-50.dark:hover:bg-gray-600
  th.py-4.px-6.font-medium.text-gray-900.whitespace-nowrap.dark:text-white[scope="row"]= item.name
  td.py-4.px-6
    p= number_to_currency(item.price/100.0, :unit => '$')    
    = item_discounts(item, discounts)
  td.py-4.px-6.text-right
    input#small-input.block.p-2.text-gray-900.bg-gray-50.rounded-lg.border.border-gray-300.sm:text-xs.focus:ring-blue-500.focus:border-blue-500.dark:bg-gray-700.dark:border-gray-600.dark:placeholder-gray-400.dark:text-white.dark:focus:ring-blue-500.dark:focus:border-blue-500 type="number" name="items[#{item.id}]" data-action="input->orders#calculate"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeeshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />
  </head>

  <body>
    <main class="container mx-auto px-4">
      <%= yield %>
    </main>
  </body>
</html>